<?php

return [
    'permissions' => [
        ['name' => 'roles.view', 'label' => 'View roles', 'group' => 'Access Control'],
        ['name' => 'roles.manage', 'label' => 'Manage roles', 'group' => 'Access Control'],
        ['name' => 'activity_logs.view', 'label' => 'View activity logs', 'group' => 'Access Control'],
        ['name' => 'currencies.view', 'label' => 'View currencies', 'group' => 'Settings'],
        ['name' => 'currencies.manage', 'label' => 'Manage currencies', 'group' => 'Settings'],
        ['name' => 'rate_indexes.view', 'label' => 'View rate indexes', 'group' => 'Settings'],
        ['name' => 'rate_indexes.manage', 'label' => 'Manage rate indexes', 'group' => 'Settings'],
        ['name' => 'tenant_users.view', 'label' => 'View tenant users', 'group' => 'User Management'],
        ['name' => 'tenant_users.manage', 'label' => 'Manage tenant users', 'group' => 'User Management'],
        ['name' => 'addresses.view', 'label' => 'View addresses', 'group' => 'User Management'],
        ['name' => 'addresses.manage', 'label' => 'Manage addresses', 'group' => 'User Management'],
        ['name' => 'customers.view', 'label' => 'View customers', 'group' => 'Commercial'],
        ['name' => 'customers.manage', 'label' => 'Manage customers', 'group' => 'Commercial'],
        ['name' => 'branches.view', 'label' => 'View branches', 'group' => 'Catalog'],
        ['name' => 'branches.manage', 'label' => 'Manage branches', 'group' => 'Catalog'],
        ['name' => 'categories.view', 'label' => 'View categories', 'group' => 'Catalog'],
        ['name' => 'categories.manage', 'label' => 'Manage categories', 'group' => 'Catalog'],
        ['name' => 'items.view', 'label' => 'View items', 'group' => 'Catalog'],
        ['name' => 'items.manage', 'label' => 'Manage items', 'group' => 'Catalog'],
        ['name' => 'promotions.view', 'label' => 'View promotions', 'group' => 'Commercial'],
        ['name' => 'promotions.manage', 'label' => 'Manage promotions', 'group' => 'Commercial'],
        ['name' => 'price_lists.view', 'label' => 'View price lists', 'group' => 'Commercial'],
        ['name' => 'price_lists.manage', 'label' => 'Manage price lists', 'group' => 'Commercial'],
        ['name' => 'pos.view', 'label' => 'View POS', 'group' => 'Commercial'],
        ['name' => 'pos.manage', 'label' => 'Manage POS', 'group' => 'Commercial'],
        ['name' => 'sliders.view', 'label' => 'View sliders', 'group' => 'Marketing'],
        ['name' => 'sliders.manage', 'label' => 'Manage sliders', 'group' => 'Marketing'],
        ['name' => 'file_manager.view', 'label' => 'View file manager', 'group' => 'Marketing'],
        ['name' => 'file_manager.manage', 'label' => 'Manage file manager', 'group' => 'Marketing'],
    ],
    'default_roles' => [
        [
            'name' => 'tenant-admin',
            'label' => 'Tenant Admin',
            'description' => 'Full access inside the selected tenant.',
            'permissions' => '*',
        ],
        [
            'name' => 'catalog-manager',
            'label' => 'Catalog Manager',
            'description' => 'Manage catalog, pricing, promotions, and sliders.',
            'permissions' => [
                'activity_logs.view',
                'currencies.view',
                'currencies.manage',
                'rate_indexes.view',
                'rate_indexes.manage',
                'branches.view',
                'branches.manage',
                'customers.view',
                'customers.manage',
                'categories.view',
                'categories.manage',
                'items.view',
                'items.manage',
                'promotions.view',
                'promotions.manage',
                'price_lists.view',
                'price_lists.manage',
                'pos.view',
                'pos.manage',
                'sliders.view',
                'sliders.manage',
                'file_manager.view',
                'file_manager.manage',
            ],
        ],
        [
            'name' => 'tenant-viewer',
            'label' => 'Tenant Viewer',
            'description' => 'Read-only access to tenant resources.',
            'permissions' => [
                'activity_logs.view',
                'currencies.view',
                'rate_indexes.view',
                'addresses.view',
                'tenant_users.view',
                'branches.view',
                'customers.view',
                'categories.view',
                'items.view',
                'promotions.view',
                'price_lists.view',
                'sliders.view',
                'file_manager.view',
            ],
        ],
    ],
];
