<?php

return [
    'permissions' => [
        ['name' => 'roles.view', 'label' => 'View roles', 'group' => 'Access Control'],
        ['name' => 'roles.create', 'label' => 'Create roles', 'group' => 'Access Control'],
        ['name' => 'roles.edit', 'label' => 'Edit roles', 'group' => 'Access Control'],
        ['name' => 'roles.delete', 'label' => 'Delete roles', 'group' => 'Access Control'],
        ['name' => 'activity_logs.view', 'label' => 'View activity logs', 'group' => 'Access Control'],
        ['name' => 'general_settings.view', 'label' => 'View general settings', 'group' => 'Settings'],
        ['name' => 'general_settings.edit', 'label' => 'Edit general settings', 'group' => 'Settings'],
        ['name' => 'currencies.view', 'label' => 'View currencies', 'group' => 'Settings'],
        ['name' => 'currencies.create', 'label' => 'Create currencies', 'group' => 'Settings'],
        ['name' => 'currencies.edit', 'label' => 'Edit currencies', 'group' => 'Settings'],
        ['name' => 'currencies.delete', 'label' => 'Delete currencies', 'group' => 'Settings'],
        ['name' => 'rate_indexes.view', 'label' => 'View rate indexes', 'group' => 'Settings'],
        ['name' => 'rate_indexes.create', 'label' => 'Create rate indexes', 'group' => 'Settings'],
        ['name' => 'rate_indexes.edit', 'label' => 'Edit rate indexes', 'group' => 'Settings'],
        ['name' => 'rate_indexes.delete', 'label' => 'Delete rate indexes', 'group' => 'Settings'],
        ['name' => 'tenant_users.view', 'label' => 'View tenant users', 'group' => 'User Management'],
        ['name' => 'tenant_users.create', 'label' => 'Create tenant users', 'group' => 'User Management'],
        ['name' => 'tenant_users.edit', 'label' => 'Edit tenant users', 'group' => 'User Management'],
        ['name' => 'tenant_users.delete', 'label' => 'Delete tenant users', 'group' => 'User Management'],
        ['name' => 'addresses.view', 'label' => 'View addresses', 'group' => 'User Management'],
        ['name' => 'addresses.create', 'label' => 'Create addresses', 'group' => 'User Management'],
        ['name' => 'addresses.edit', 'label' => 'Edit addresses', 'group' => 'User Management'],
        ['name' => 'addresses.delete', 'label' => 'Delete addresses', 'group' => 'User Management'],
        ['name' => 'customers.view', 'label' => 'View customers', 'group' => 'Commercial'],
        ['name' => 'customers.create', 'label' => 'Create customers', 'group' => 'Commercial'],
        ['name' => 'customers.edit', 'label' => 'Edit customers', 'group' => 'Commercial'],
        ['name' => 'customers.delete', 'label' => 'Delete customers', 'group' => 'Commercial'],
        ['name' => 'purchase_orders.view', 'label' => 'View purchase orders', 'group' => 'Commercial'],
        ['name' => 'purchase_orders.create', 'label' => 'Create purchase orders', 'group' => 'Commercial'],
        ['name' => 'purchase_orders.edit', 'label' => 'Edit purchase orders', 'group' => 'Commercial'],
        ['name' => 'purchase_orders.delete', 'label' => 'Delete purchase orders', 'group' => 'Commercial'],
        ['name' => 'purchase_orders.receive', 'label' => 'Receive and stock in purchase orders', 'group' => 'Commercial'],
        ['name' => 'branches.view', 'label' => 'View branches', 'group' => 'Catalog'],
        ['name' => 'branches.create', 'label' => 'Create branches', 'group' => 'Catalog'],
        ['name' => 'branches.edit', 'label' => 'Edit branches', 'group' => 'Catalog'],
        ['name' => 'branches.delete', 'label' => 'Delete branches', 'group' => 'Catalog'],
        ['name' => 'categories.view', 'label' => 'View categories', 'group' => 'Catalog'],
        ['name' => 'categories.create', 'label' => 'Create categories', 'group' => 'Catalog'],
        ['name' => 'categories.edit', 'label' => 'Edit categories', 'group' => 'Catalog'],
        ['name' => 'categories.delete', 'label' => 'Delete categories', 'group' => 'Catalog'],
        ['name' => 'units_of_measure.view', 'label' => 'View units of measure', 'group' => 'Catalog'],
        ['name' => 'units_of_measure.create', 'label' => 'Create units of measure', 'group' => 'Catalog'],
        ['name' => 'units_of_measure.edit', 'label' => 'Edit units of measure', 'group' => 'Catalog'],
        ['name' => 'units_of_measure.delete', 'label' => 'Delete units of measure', 'group' => 'Catalog'],
        ['name' => 'uom_groups.view', 'label' => 'View UOM groups', 'group' => 'Catalog'],
        ['name' => 'uom_groups.create', 'label' => 'Create UOM groups', 'group' => 'Catalog'],
        ['name' => 'uom_groups.edit', 'label' => 'Edit UOM groups', 'group' => 'Catalog'],
        ['name' => 'uom_groups.delete', 'label' => 'Delete UOM groups', 'group' => 'Catalog'],
        ['name' => 'item_variations.view', 'label' => 'View item variations', 'group' => 'Catalog'],
        ['name' => 'item_variations.create', 'label' => 'Create item variations', 'group' => 'Catalog'],
        ['name' => 'item_variations.edit', 'label' => 'Edit item variations', 'group' => 'Catalog'],
        ['name' => 'item_variations.delete', 'label' => 'Delete item variations', 'group' => 'Catalog'],
        ['name' => 'item_options.view', 'label' => 'View item options', 'group' => 'Catalog'],
        ['name' => 'item_options.create', 'label' => 'Create item options', 'group' => 'Catalog'],
        ['name' => 'item_options.edit', 'label' => 'Edit item options', 'group' => 'Catalog'],
        ['name' => 'item_options.delete', 'label' => 'Delete item options', 'group' => 'Catalog'],
        ['name' => 'items.view', 'label' => 'View items', 'group' => 'Catalog'],
        ['name' => 'items.create', 'label' => 'Create items', 'group' => 'Catalog'],
        ['name' => 'items.edit', 'label' => 'Edit items', 'group' => 'Catalog'],
        ['name' => 'items.delete', 'label' => 'Delete items', 'group' => 'Catalog'],
        ['name' => 'promotions.view', 'label' => 'View promotions', 'group' => 'Commercial'],
        ['name' => 'promotions.create', 'label' => 'Create promotions', 'group' => 'Commercial'],
        ['name' => 'promotions.edit', 'label' => 'Edit promotions', 'group' => 'Commercial'],
        ['name' => 'promotions.delete', 'label' => 'Delete promotions', 'group' => 'Commercial'],
        ['name' => 'price_lists.view', 'label' => 'View price lists', 'group' => 'Commercial'],
        ['name' => 'price_lists.create', 'label' => 'Create price lists', 'group' => 'Commercial'],
        ['name' => 'price_lists.edit', 'label' => 'Edit price lists', 'group' => 'Commercial'],
        ['name' => 'price_lists.delete', 'label' => 'Delete price lists', 'group' => 'Commercial'],
        ['name' => 'pos.view', 'label' => 'View POS', 'group' => 'Commercial'],
        ['name' => 'pos.create', 'label' => 'Create POS sales', 'group' => 'Commercial'],
        ['name' => 'pos.edit', 'label' => 'Edit POS sales', 'group' => 'Commercial'],
        ['name' => 'pos.delete', 'label' => 'Delete POS sales', 'group' => 'Commercial'],
        ['name' => 'sliders.view', 'label' => 'View sliders', 'group' => 'Marketing'],
        ['name' => 'sliders.create', 'label' => 'Create sliders', 'group' => 'Marketing'],
        ['name' => 'sliders.edit', 'label' => 'Edit sliders', 'group' => 'Marketing'],
        ['name' => 'sliders.delete', 'label' => 'Delete sliders', 'group' => 'Marketing'],
        ['name' => 'file_manager.view', 'label' => 'View file manager', 'group' => 'Marketing'],
        ['name' => 'file_manager.create', 'label' => 'Create files and folders', 'group' => 'Marketing'],
        ['name' => 'file_manager.edit', 'label' => 'Edit files and folders', 'group' => 'Marketing'],
        ['name' => 'file_manager.delete', 'label' => 'Delete files and folders', 'group' => 'Marketing'],
        ['name' => 'reports.view', 'label' => 'View reports', 'group' => 'Reports'],
        ['name' => 'reports.export', 'label' => 'Export reports', 'group' => 'Reports'],
    ],
    'default_roles' => [
        [
            'name' => 'tenant-admin',
            'label' => 'Tenant Admin',
            'description' => 'Full access inside the selected tenant.',
            'permissions' => '*',
        ],
        [
            'name' => 'catalog-manager',
            'label' => 'Catalog Manager',
            'description' => 'Manage catalog, pricing, promotions, and sliders.',
            'permissions' => [
                'activity_logs.view',
                'currencies.view',
                'currencies.create',
                'currencies.edit',
                'currencies.delete',
                'rate_indexes.view',
                'rate_indexes.create',
                'rate_indexes.edit',
                'rate_indexes.delete',
                'branches.view',
                'branches.create',
                'branches.edit',
                'branches.delete',
                'customers.view',
                'customers.create',
                'customers.edit',
                'customers.delete',
                'purchase_orders.view',
                'purchase_orders.create',
                'purchase_orders.edit',
                'purchase_orders.delete',
                'purchase_orders.receive',
                'categories.view',
                'categories.create',
                'categories.edit',
                'categories.delete',
                'units_of_measure.view',
                'units_of_measure.create',
                'units_of_measure.edit',
                'units_of_measure.delete',
                'uom_groups.view',
                'uom_groups.create',
                'uom_groups.edit',
                'uom_groups.delete',
                'item_variations.view',
                'item_variations.create',
                'item_variations.edit',
                'item_variations.delete',
                'item_options.view',
                'item_options.create',
                'item_options.edit',
                'item_options.delete',
                'items.view',
                'items.create',
                'items.edit',
                'items.delete',
                'promotions.view',
                'promotions.create',
                'promotions.edit',
                'promotions.delete',
                'price_lists.view',
                'price_lists.create',
                'price_lists.edit',
                'price_lists.delete',
                'pos.view',
                'pos.create',
                'pos.edit',
                'pos.delete',
                'sliders.view',
                'sliders.create',
                'sliders.edit',
                'sliders.delete',
                'file_manager.view',
                'file_manager.create',
                'file_manager.edit',
                'file_manager.delete',
                'reports.view',
                'reports.export',
            ],
        ],
        [
            'name' => 'tenant-viewer',
            'label' => 'Tenant Viewer',
            'description' => 'Read-only access to tenant resources.',
            'permissions' => [
                'activity_logs.view',
                'currencies.view',
                'rate_indexes.view',
                'addresses.view',
                'tenant_users.view',
                'branches.view',
                'customers.view',
                'purchase_orders.view',
                'categories.view',
                'units_of_measure.view',
                'uom_groups.view',
                'item_variations.view',
                'item_options.view',
                'items.view',
                'promotions.view',
                'price_lists.view',
                'sliders.view',
                'file_manager.view',
                'reports.view',
            ],
        ],
    ],
];
