version: '3.8'

services:
  app1:
    build:
      context: ./php
    container_name: laravel_app1
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  app2:
    build:
      context: ./php
    container_name: laravel_app2
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8880:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    external: true