services:
  app1:
    build:
      context: ./php
    container_name: laravel_app1
    command: php-fpm
    volumes:
      - .:/var/www/html
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - app-network

  app2:
    build:
      context: ./php
    container_name: laravel_app2
    command: php-fpm
    volumes:
      - .:/var/www/html
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - app-network

  queue:
    build:
      context: ./php
    container_name: laravel_queue
    command: /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "${RUNNING_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    external: true
