services:
  minio:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio
    restart: unless-stopped
    env_file:
      - .env
    command: server /data --console-address ":9001"
    ports:
      - "${S3_API_PORT}:9000"       # S3 API
      - "${WEB_CONSOLE_PORT}:9001"  # Web Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${S3_API_PORT}/minio/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

volumes:
  minio_data:

networks:
  app-network:
    external: true