version: '3.9'

networks:
  fastapi-network:

services:
  mariadb:
    container_name: mariadb-fastapi
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER}                   
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - fastapi-network

  phpmyadmin:
    container_name: phpmyadmin-fastapi
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb
    networks:
      - fastapi-network

  fastapi-app:
    build:
      context: .
    container_name: fastapi-app
    volumes:
      - ./app:/app  # Mount `app` directly to container's /app
    ports:
      - "${BAKEND_PORT}:8000"
    env_file:
      - .env
    # entrypoint: ["/entrypoint.sh"]  
    command: >
      python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    depends_on:
      - mariadb
    networks:
      - fastapi-network 