services: 
  fastapi-app:
    build:
      context: .
    container_name: fastapi-app
    restart: always
    volumes:
      - ./app:/app  # Mount `app` directly to container's /app
    ports:
      - "${RUNNING_PORT}:8000"
    env_file:
      - .env
    # entrypoint: ["/entrypoint.sh"]  
    command: >
      python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network 
      
networks:
  app-network:
    external: true