version: '3.8'

services:
  ui5-app:
    container_name: frontend-ui5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:9090"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "ui5 serve --port=9090 --accept-remote-connections"